name: Build and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          java-package: jdk
      - name: Build
        run: mvn -B -e install -Dapp.version=${GITHUB_REF#refs/heads/}
        env:
          GH: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: javadoc
          project: maven
          custom-command: cp -r /home/runner/work/BHoM_Java/BHoM_Java/bhom/target/site/apidocs ./javadoc
