name: Build and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          java-package: jdk
      - name: Build
        run: mvn -B -e install -Dapp.version=${GITHUB_REF#refs/heads/}
        env:
          GH: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy JavaDoc
        run: cp -r /home/runner/work/BHoM_Java/BHoM_Java/bhom/target/site/apidocs /home/runner/work/BHoM_Java/BHoM_Java/public
      - name: Deploy Javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
